apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: deployment-template
spec:
  configPath: .status.conditions[?(@.type=="Ready")].status
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: $(workload.metadata.name)$
    spec:
      selector:
        matchLabels:
          app: $(workload.metadata.name)$
      replicas: 2
      template:
        metadata:
          labels:
            app: $(workload.metadata.name)$
        spec:
          containers:
            - name: app-container
              image: $(sources.image.url)$
              ports:
                - containerPort: 80
                
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: my-service
    spec:
      selector:
        app: $(workload.metadata.name)$
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
