apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: simple-git-source-supply-chain
spec:
  selector:
    app: simple-app
  resources:
    - name: source-code
      templateRef:
        kind: ClusterSourceTemplate
        name: flux-git-source-template